version: '3.4'

services:
  smtp:
    image: smtp2dev
    build:
      context: .
      dockerfile: smtp2dev-docker/Dockerfile
    ports:
      - 3000:80

  webapplication2:
    image: ${DOCKER_REGISTRY-}webapplication2
    build:
      context: .
      dockerfile: WebApplication2/Dockerfile

